2.1.1

In [ ]:
import torch

In [6]:
x = torch.arange(12)
x

SyntaxError: invalid syntax (3555013584.py, line 1)

In [8]:
x.shape

torch.Size([12])

In [10]:
x.numel()

12

In [11]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.randn(3, 4)

tensor([[ 0.8041,  0.7093, -2.0391,  2.3375],
        [ 0.4624, -0.5518,  1.4794,  0.3840],
        [-1.4021,  0.8038, -1.3058,  0.3401]])

In [16]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

2.1.2

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [18]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [19]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [20]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
X.sum()

tensor(66.)

2.1.3

In [23]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [24]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

2.1.4

In [25]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [26]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

2.1.5

In [28]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [32]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
# Z = X + Y
print('id(Z):', id(Z))

id(Z): 2442904398800
id(Z): 2442904398800


In [34]:
before = id(X)
X += Y
id(X) == before

True

2.1.6

In [35]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [36]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

2.1.8

In [37]:
X, Y

(tensor([[40., 38., 44., 42.],
         [38., 40., 42., 44.],
         [32., 33., 34., 35.]]),
 tensor([[14., 13., 16., 15.],
         [13., 14., 15., 16.],
         [12., 12., 12., 12.]]))

In [39]:
# X < Y
X > Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [40]:
a = torch.arange(3).reshape(3, 1, 1)
b = torch.arange(6).reshape(1, 3, 2)
a, b

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]),
 tensor([[[0, 1],
          [2, 3],
          [4, 5]]]))

In [41]:
a + b

tensor([[[0, 1],
         [2, 3],
         [4, 5]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[2, 3],
         [4, 5],
         [6, 7]]])