2.5.1

In [2]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
x.grad  # 默认值是None

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

In [7]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

2.5.2

In [18]:
x.grad.zero_()
y = x * x
# y.sum().backward()
y.backward( torch.ones( len(x) ) )
x.grad

tensor([0., 2., 4., 6.])

In [16]:
x.grad == 2 * x

tensor([True, True, True, True])

2.5.3

In [20]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [24]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

2.5.4

In [25]:
def f(a):
    b = a * 2

    while b.norm() < 1000:
        b = b * 2

    if b.sum() > 0:
        c = b
    else:
        c = 100 * b

    return c

In [26]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [28]:
a.grad == d / a

tensor(True)

2.5.6