5.4.1

In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-9.3132e-09, grad_fn=<MeanBackward0>)

5.4.2

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [19]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.2868, -1.5277, -0.3811],
        [ 0.0040, -0.1786,  0.9602],
        [-1.0728, -0.6509,  0.6404],
        [ 0.9071,  0.2495, -1.3448],
        [ 0.0545,  1.1558, -0.2713]], requires_grad=True)

In [20]:
linear(torch.rand(2, 5))

tensor([[0.2521, 0.1367, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [21]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [2.3276]])